
POST http://localhost:8080/branchOffice/1
Accept: application/json
Content-Type: application/json

{
  "storename": "Buy at home",
  "descripcion": "Perez",
  "neighbourId": 1,
  "street": "Av. Busch",
  "number": "444-A",
  "reference": "Entrando media cuadra de Av. Busch"
}